// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.Property<long>("AlunosalunoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TurmasturmaId")
                        .HasColumnType("bigint");

                    b.HasKey("AlunosalunoId", "TurmasturmaId");

                    b.HasIndex("TurmasturmaId");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("backend.Models.Aluno", b =>
                {
                    b.Property<long>("alunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("aluno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("alunoId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<long?>("grupoId")
                        .HasColumnType("bigint");

                    b.Property<int>("idade")
                        .HasColumnType("integer")
                        .HasColumnName("idade");

                    b.Property<string>("nomeAluno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_aluno");

                    b.Property<int>("ra")
                        .HasColumnType("integer")
                        .HasColumnName("ra");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sobrenome");

                    b.HasKey("alunoId");

                    b.HasIndex("grupoId");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("backend.Models.Atividade", b =>
                {
                    b.Property<long>("ativId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_atividade");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ativId"));

                    b.Property<long>("alunoId")
                        .HasColumnType("bigint")
                        .HasColumnName("aluno_id");

                    b.Property<long>("cicloId")
                        .HasColumnType("bigint")
                        .HasColumnName("ciclo_id");

                    b.Property<string>("nomeAtividade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_atividade");

                    b.Property<float>("notaAtividade")
                        .HasColumnType("real")
                        .HasColumnName("nota_atividade");

                    b.HasKey("ativId");

                    b.HasIndex("alunoId");

                    b.HasIndex("cicloId");

                    b.ToTable("Atividade");
                });

            modelBuilder.Entity("backend.Models.Ciclo", b =>
                {
                    b.Property<long>("idCiclo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ciclo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idCiclo"));

                    b.Property<long?>("alunoId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("dataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("dataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("nomeCiclo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_ciclo");

                    b.Property<float>("pesoNota")
                        .HasColumnType("real")
                        .HasColumnName("peso_nota");

                    b.Property<long>("turmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("turma_id");

                    b.HasKey("idCiclo");

                    b.HasIndex("alunoId");

                    b.HasIndex("turmaId");

                    b.ToTable("Ciclo");
                });

            modelBuilder.Entity("backend.Models.Grupo", b =>
                {
                    b.Property<long>("grupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("grupoId"));

                    b.Property<string>("nomeGrupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_grupo");

                    b.HasKey("grupoId");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("backend.Models.Turma", b =>
                {
                    b.Property<long>("turmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("turma_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("turmaId"));

                    b.Property<string>("nomeTurma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_turma");

                    b.Property<int>("qtdAlunos")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_aluno");

                    b.Property<int>("qtdCiclos")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_ciclos");

                    b.HasKey("turmaId");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.HasOne("backend.Models.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunosalunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasturmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Aluno", b =>
                {
                    b.HasOne("backend.Models.Grupo", null)
                        .WithMany("Alunos")
                        .HasForeignKey("grupoId");
                });

            modelBuilder.Entity("backend.Models.Atividade", b =>
                {
                    b.HasOne("backend.Models.Aluno", "Aluno")
                        .WithMany("Atividades")
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Ciclo", "Ciclo")
                        .WithMany("Atividades")
                        .HasForeignKey("cicloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Ciclo");
                });

            modelBuilder.Entity("backend.Models.Ciclo", b =>
                {
                    b.HasOne("backend.Models.Aluno", null)
                        .WithMany("Ciclos")
                        .HasForeignKey("alunoId");

                    b.HasOne("backend.Models.Turma", "Turma")
                        .WithMany("Ciclos")
                        .HasForeignKey("turmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("backend.Models.Aluno", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Ciclos");
                });

            modelBuilder.Entity("backend.Models.Ciclo", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("backend.Models.Grupo", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("backend.Models.Turma", b =>
                {
                    b.Navigation("Ciclos");
                });
#pragma warning restore 612, 618
        }
    }
}
